import type { EquipmentType as PrismaEquipmentType } from '@/prisma/generated/client';

export const supportedAssessmentEquipmentValues = [
  'DUMBBELL',
  'BARBELL',
  'MACHINE',
  'CABLE',
  'BODYWEIGHT',
] as const satisfies readonly PrismaEquipmentType[];

export type EquipmentType = (typeof supportedAssessmentEquipmentValues)[number];

export const exerciseCatalogKeys = [
  'back_squat',
  'goblet_squat',
  'leg_press',
  'bodyweight_squat',
  'romanian_deadlift',
  'dumbbell_romanian_deadlift',
  'cable_pull_through',
  'hip_bridge',
  'bench_press',
  'dumbbell_bench_press',
  'chest_press',
  'push_up',
  'barbell_row',
  'one_arm_dumbbell_row',
  'seated_cable_row',
  'inverted_row',
  'overhead_press',
  'dumbbell_shoulder_press',
  'machine_shoulder_press',
  'pike_push_up',
  'pull_up',
  'lat_pulldown',
  'cable_pulldown',
  'cable_lateral_raise',
  'dumbbell_lateral_raise',
  'machine_lateral_raise',
  'leg_extension',
  'reverse_lunge',
  'split_squat',
  'leg_curl',
  'sliding_leg_curl',
  'single_leg_hip_bridge',
  'cable_curl',
  'dumbbell_curl',
  'barbell_curl',
  'bodyweight_curl',
  'cable_triceps_extension',
  'dumbbell_overhead_extension',
  'close_grip_push_up',
  'standing_calf_raise',
  'dumbbell_calf_raise',
  'machine_calf_raise',
  'cable_crunch',
  'plank',
  'dead_bug',
] as const;

export type ExerciseCatalogKey = (typeof exerciseCatalogKeys)[number];

export const exerciseRequiredEquipment = {
  back_squat: 'BARBELL',
  goblet_squat: 'DUMBBELL',
  leg_press: 'MACHINE',
  bodyweight_squat: 'BODYWEIGHT',
  romanian_deadlift: 'BARBELL',
  dumbbell_romanian_deadlift: 'DUMBBELL',
  cable_pull_through: 'CABLE',
  hip_bridge: 'BODYWEIGHT',
  bench_press: 'BARBELL',
  dumbbell_bench_press: 'DUMBBELL',
  chest_press: 'MACHINE',
  push_up: 'BODYWEIGHT',
  barbell_row: 'BARBELL',
  one_arm_dumbbell_row: 'DUMBBELL',
  seated_cable_row: 'CABLE',
  inverted_row: 'BODYWEIGHT',
  overhead_press: 'BARBELL',
  dumbbell_shoulder_press: 'DUMBBELL',
  machine_shoulder_press: 'MACHINE',
  pike_push_up: 'BODYWEIGHT',
  pull_up: 'BODYWEIGHT',
  lat_pulldown: 'MACHINE',
  cable_pulldown: 'CABLE',
  cable_lateral_raise: 'CABLE',
  dumbbell_lateral_raise: 'DUMBBELL',
  machine_lateral_raise: 'MACHINE',
  leg_extension: 'MACHINE',
  reverse_lunge: 'BODYWEIGHT',
  split_squat: 'BODYWEIGHT',
  leg_curl: 'MACHINE',
  sliding_leg_curl: 'BODYWEIGHT',
  single_leg_hip_bridge: 'BODYWEIGHT',
  cable_curl: 'CABLE',
  dumbbell_curl: 'DUMBBELL',
  barbell_curl: 'BARBELL',
  bodyweight_curl: 'BODYWEIGHT',
  cable_triceps_extension: 'CABLE',
  dumbbell_overhead_extension: 'DUMBBELL',
  close_grip_push_up: 'BODYWEIGHT',
  standing_calf_raise: 'BODYWEIGHT',
  dumbbell_calf_raise: 'DUMBBELL',
  machine_calf_raise: 'MACHINE',
  cable_crunch: 'CABLE',
  plank: 'BODYWEIGHT',
  dead_bug: 'BODYWEIGHT',
} as const satisfies Record<ExerciseCatalogKey, EquipmentType>;
