import { EquipmentType, ExerciseCategory, MuscleGroup } from '@/lib/prisma-client';

import type { EquipmentType as StrengthEquipmentType, ExerciseCatalogKey } from './exercise-keys';

export const movementPatterns = [
  'SQUAT',
  'HINGE',
  'HORIZONTAL_PUSH',
  'HORIZONTAL_PULL',
  'VERTICAL_PUSH',
  'VERTICAL_PULL',
  'LATERAL_SHOULDER',
  'KNEE_ISOLATION',
  'HAMSTRING_ISOLATION',
  'BICEPS',
  'TRICEPS',
  'CALVES',
  'TRUNK',
] as const;

export type MovementPattern = (typeof movementPatterns)[number];

export type StrengthCatalogExercise = {
  key: ExerciseCatalogKey;
  name: string;
  aliases: readonly string[];
  muscleGroup: MuscleGroup;
  movementPattern: MovementPattern;
  category: ExerciseCategory;
  equipmentType: StrengthEquipmentType;
  usesBodyweight: boolean;
  defaultRestSec: number;
  priority: number;
};

export type ExerciseCatalogEntry = StrengthCatalogExercise;

function catalogExercise(
  value: Omit<StrengthCatalogExercise, 'usesBodyweight'>,
): StrengthCatalogExercise {
  return {
    ...value,
    usesBodyweight: value.equipmentType === EquipmentType.BODYWEIGHT,
  };
}

export const STRENGTH_EXERCISE_CATALOG: readonly StrengthCatalogExercise[] = [
  catalogExercise({
    key: 'back_squat',
    name: 'Back Squat',
    aliases: ['Squat', 'Barbell Back Squat', 'Back squat (barbell)', 'Squats · Barbell'],
    muscleGroup: MuscleGroup.QUADS,
    movementPattern: 'SQUAT',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BARBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'goblet_squat',
    name: 'Goblet Squat',
    aliases: ['Dumbbell Goblet Squat', 'Goblet squat'],
    muscleGroup: MuscleGroup.QUADS,
    movementPattern: 'SQUAT',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'leg_press',
    name: 'Leg Press',
    aliases: ['Machine Leg Press', 'Leg Press · Machine', 'Leg press (45 deg)'],
    muscleGroup: MuscleGroup.QUADS,
    movementPattern: 'SQUAT',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.MACHINE,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'bodyweight_squat',
    name: 'Bodyweight Squat',
    aliases: ['Air Squat'],
    muscleGroup: MuscleGroup.QUADS,
    movementPattern: 'SQUAT',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    aliases: ['Barbell Romanian Deadlift', 'Romanian Deadlifts · Barbell'],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    movementPattern: 'HINGE',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BARBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'dumbbell_romanian_deadlift',
    name: 'Dumbbell Romanian Deadlift',
    aliases: ['Dumbbell RDL'],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    movementPattern: 'HINGE',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'cable_pull_through',
    name: 'Cable Pull Through',
    aliases: ['Cable Pull-through'],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    movementPattern: 'HINGE',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.CABLE,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'hip_bridge',
    name: 'Hip Bridge',
    aliases: ['Glute Bridge'],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    movementPattern: 'HINGE',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'bench_press',
    name: 'Bench Press',
    aliases: ['Barbell bench press', 'Bench Press · Barbell', 'Bench Press (Barbell)'],
    muscleGroup: MuscleGroup.CHEST,
    movementPattern: 'HORIZONTAL_PUSH',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BARBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    aliases: ['Bench Press · Dumbbells', 'Dumbbell bench press', 'Flat dumbbell bench press'],
    muscleGroup: MuscleGroup.CHEST,
    movementPattern: 'HORIZONTAL_PUSH',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'chest_press',
    name: 'Chest Press',
    aliases: ['Machine Chest Press', 'Machine chest press'],
    muscleGroup: MuscleGroup.CHEST,
    movementPattern: 'HORIZONTAL_PUSH',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.MACHINE,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'push_up',
    name: 'Push-up',
    aliases: ['Push Up', 'Push-up (bodyweight)'],
    muscleGroup: MuscleGroup.CHEST,
    movementPattern: 'HORIZONTAL_PUSH',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'barbell_row',
    name: 'Barbell Row',
    aliases: ['Bent-over barbell row', 'Bent Over Barbell Row'],
    muscleGroup: MuscleGroup.BACK_THICKNESS,
    movementPattern: 'HORIZONTAL_PULL',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BARBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'one_arm_dumbbell_row',
    name: 'One-arm Dumbbell Row',
    aliases: ['One Arm Dumbbell Row', 'Single-arm dumbbell row', 'One-Arm Rows · Dumbbells'],
    muscleGroup: MuscleGroup.BACK_THICKNESS,
    movementPattern: 'HORIZONTAL_PULL',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'seated_cable_row',
    name: 'Seated Cable Row',
    aliases: [
      'Seated cable row (close handles)',
      'Rows with Close Grip · Cable',
      'Rows with Reverse Grip · Cable',
      'Rows with Wide Neutral Grip · Cable',
    ],
    muscleGroup: MuscleGroup.BACK_THICKNESS,
    movementPattern: 'HORIZONTAL_PULL',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.CABLE,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'inverted_row',
    name: 'Inverted Row',
    aliases: ['Bodyweight Row'],
    muscleGroup: MuscleGroup.BACK_THICKNESS,
    movementPattern: 'HORIZONTAL_PULL',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'overhead_press',
    name: 'Overhead Press',
    aliases: [
      'Barbell Overhead Press',
      'Military Press',
      'Standing barbell overhead press',
      'Standing Shoulder Press · Barbell',
    ],
    muscleGroup: MuscleGroup.SHOULDERS_FRONT,
    movementPattern: 'VERTICAL_PUSH',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BARBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    aliases: [
      'Seated dumbbell overhead press',
      'Dumbbell Overhead Press',
      'Seated Shoulder Press with Close Grip · Dumbbells',
      'Seated Shoulder Press · Dumbbells',
    ],
    muscleGroup: MuscleGroup.SHOULDERS_FRONT,
    movementPattern: 'VERTICAL_PUSH',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    aliases: ['Shoulder Press Machine'],
    muscleGroup: MuscleGroup.SHOULDERS_FRONT,
    movementPattern: 'VERTICAL_PUSH',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.MACHINE,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'pike_push_up',
    name: 'Pike Push-up',
    aliases: ['Pike Push Up'],
    muscleGroup: MuscleGroup.SHOULDERS_FRONT,
    movementPattern: 'VERTICAL_PUSH',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'pull_up',
    name: 'Pull-up',
    aliases: [
      'Pull-ups',
      'Pronated pull-ups (weighted if possible)',
      'Pull-Ups with Wide Overhand Grip · Bodyweight',
    ],
    muscleGroup: MuscleGroup.BACK_WIDTH,
    movementPattern: 'VERTICAL_PULL',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'lat_pulldown',
    name: 'Lat Pulldown',
    aliases: ['Lat pulldown (wide grip)', 'Wide-grip Lat Pulldown'],
    muscleGroup: MuscleGroup.BACK_WIDTH,
    movementPattern: 'VERTICAL_PULL',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.MACHINE,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'cable_pulldown',
    name: 'Cable Pulldown',
    aliases: [
      'Cable Lat Pulldown',
      'Lat Pulldowns with Close Neutral Grip · Cable',
      'Lat Pulldowns with Close Overhand Grip · Cable',
    ],
    muscleGroup: MuscleGroup.BACK_WIDTH,
    movementPattern: 'VERTICAL_PULL',
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.CABLE,
    defaultRestSec: 150,
    priority: 0,
  }),
  catalogExercise({
    key: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    aliases: ['Cable lateral raises'],
    muscleGroup: MuscleGroup.SHOULDERS_LATERAL,
    movementPattern: 'LATERAL_SHOULDER',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.CABLE,
    defaultRestSec: 75,
    priority: 10,
  }),
  catalogExercise({
    key: 'dumbbell_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    aliases: ['Dumbbell Lateral Raises', 'Dumbbell lateral raise', 'Lateral Raises · Dumbbells'],
    muscleGroup: MuscleGroup.SHOULDERS_LATERAL,
    movementPattern: 'LATERAL_SHOULDER',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 75,
    priority: 10,
  }),
  catalogExercise({
    key: 'machine_lateral_raise',
    name: 'Machine Lateral Raise',
    aliases: ['Lateral Raise Machine'],
    muscleGroup: MuscleGroup.SHOULDERS_LATERAL,
    movementPattern: 'LATERAL_SHOULDER',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.MACHINE,
    defaultRestSec: 75,
    priority: 10,
  }),
  catalogExercise({
    key: 'leg_extension',
    name: 'Leg Extension',
    aliases: ['Leg extension', 'Leg Extensions · Machine'],
    muscleGroup: MuscleGroup.QUADS,
    movementPattern: 'KNEE_ISOLATION',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.MACHINE,
    defaultRestSec: 75,
    priority: 60,
  }),
  catalogExercise({
    key: 'reverse_lunge',
    name: 'Reverse Lunge',
    aliases: ['Bodyweight Reverse Lunge'],
    muscleGroup: MuscleGroup.QUADS,
    movementPattern: 'KNEE_ISOLATION',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 60,
  }),
  catalogExercise({
    key: 'split_squat',
    name: 'Split Squat',
    aliases: [
      'Bodyweight Split Squat',
      'Bulgarian split squat',
      'Bulgarian Split Squats · Dumbbells',
    ],
    muscleGroup: MuscleGroup.QUADS,
    movementPattern: 'KNEE_ISOLATION',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 60,
  }),
  catalogExercise({
    key: 'leg_curl',
    name: 'Leg Curl',
    aliases: [
      'Lying Leg Curl',
      'Seated Leg Curl',
      'Lying leg curl',
      'Seated leg curl',
      'Leg Curls on Leg Extension Machine · Machine',
      'Lying Leg Curls · Machine',
    ],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    movementPattern: 'HAMSTRING_ISOLATION',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.MACHINE,
    defaultRestSec: 75,
    priority: 70,
  }),
  catalogExercise({
    key: 'sliding_leg_curl',
    name: 'Sliding Leg Curl',
    aliases: ['Bodyweight Sliding Leg Curl'],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    movementPattern: 'HAMSTRING_ISOLATION',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 70,
  }),
  catalogExercise({
    key: 'single_leg_hip_bridge',
    name: 'Single-leg Hip Bridge',
    aliases: ['Single Leg Hip Bridge'],
    muscleGroup: MuscleGroup.HAMSTRINGS,
    movementPattern: 'HAMSTRING_ISOLATION',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 70,
  }),
  catalogExercise({
    key: 'cable_curl',
    name: 'Cable Curl',
    aliases: [
      'Cable Biceps Curl',
      'Standing cable curl (straight bar)',
      'Behind-the-Back Curls · Cable',
    ],
    muscleGroup: MuscleGroup.BICEPS,
    movementPattern: 'BICEPS',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.CABLE,
    defaultRestSec: 75,
    priority: 30,
  }),
  catalogExercise({
    key: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    aliases: ['Incline dumbbell curl (bench 60 deg)', 'Dumbbell Biceps Curl'],
    muscleGroup: MuscleGroup.BICEPS,
    movementPattern: 'BICEPS',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 75,
    priority: 30,
  }),
  catalogExercise({
    key: 'barbell_curl',
    name: 'Barbell Curl',
    aliases: ['EZ-bar curl', 'EZ Bar Curl'],
    muscleGroup: MuscleGroup.BICEPS,
    movementPattern: 'BICEPS',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BARBELL,
    defaultRestSec: 75,
    priority: 30,
  }),
  catalogExercise({
    key: 'bodyweight_curl',
    name: 'Bodyweight Curl',
    aliases: ['Bodyweight Biceps Curl'],
    muscleGroup: MuscleGroup.BICEPS,
    movementPattern: 'BICEPS',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 30,
  }),
  catalogExercise({
    key: 'cable_triceps_extension',
    name: 'Cable Triceps Extension',
    aliases: [
      'Triceps pushdown (rope)',
      'Cable Triceps Pushdown',
      'Triceps Pushdowns with Rope · Cable',
      'Overhead cable triceps extension',
    ],
    muscleGroup: MuscleGroup.TRICEPS,
    movementPattern: 'TRICEPS',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.CABLE,
    defaultRestSec: 75,
    priority: 40,
  }),
  catalogExercise({
    key: 'dumbbell_overhead_extension',
    name: 'Dumbbell Overhead Extension',
    aliases: ['Overhead Dumbbell Triceps Extension'],
    muscleGroup: MuscleGroup.TRICEPS,
    movementPattern: 'TRICEPS',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 75,
    priority: 40,
  }),
  catalogExercise({
    key: 'close_grip_push_up',
    name: 'Close-grip Push-up',
    aliases: ['Close Grip Push-up', 'Diamond Push-up'],
    muscleGroup: MuscleGroup.TRICEPS,
    movementPattern: 'TRICEPS',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 40,
  }),
  catalogExercise({
    key: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    aliases: ['Bodyweight Standing Calf Raise', 'Standing calf raise (or machine)'],
    muscleGroup: MuscleGroup.CALVES,
    movementPattern: 'CALVES',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 50,
  }),
  catalogExercise({
    key: 'dumbbell_calf_raise',
    name: 'Dumbbell Calf Raise',
    aliases: ['Dumbbell Standing Calf Raise'],
    muscleGroup: MuscleGroup.CALVES,
    movementPattern: 'CALVES',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 75,
    priority: 50,
  }),
  catalogExercise({
    key: 'machine_calf_raise',
    name: 'Machine Calf Raise',
    aliases: [
      'Standing calf raise machine',
      'Seated calf raise machine',
      'Seated Calf Raises · Machine',
    ],
    muscleGroup: MuscleGroup.CALVES,
    movementPattern: 'CALVES',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.MACHINE,
    defaultRestSec: 75,
    priority: 50,
  }),
  catalogExercise({
    key: 'cable_crunch',
    name: 'Cable Crunch',
    aliases: ['Cable crunch (kneeling)', 'Kneeling Cable Crunch'],
    muscleGroup: MuscleGroup.ABS,
    movementPattern: 'TRUNK',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.CABLE,
    defaultRestSec: 75,
    priority: 20,
  }),
  catalogExercise({
    key: 'plank',
    name: 'Plank',
    aliases: ['Front Plank', 'Plank + side plank'],
    muscleGroup: MuscleGroup.ABS,
    movementPattern: 'TRUNK',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 20,
  }),
  catalogExercise({
    key: 'dead_bug',
    name: 'Dead Bug',
    aliases: ['Deadbug'],
    muscleGroup: MuscleGroup.ABS,
    movementPattern: 'TRUNK',
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    priority: 20,
  }),
];

export const EXERCISE_CATALOG = STRENGTH_EXERCISE_CATALOG;
